### ISSUE TITLE
Add some design to the Press page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#146]
Currently http://www.code-conf.com/press/ looks like this:

![image](https://cloud.githubusercontent.com/assets/155492/15043661/26cdb942-12cf-11e6-8e93-a0b5d5f39d57.png)

It needs

- [ ] A bit of love
- [ ] A line in the footer (in the info category)

**Comment by illus0r** [comment]
@jonnycoull 
still need?

**Comment by jonnycoull** [comment]
@illus0r yes, but I need to update there press materials so hold off for now.

**Comment by jonnycoull** [comment]
@illus0r will create a new banner image for this page.

**Comment by illus0r** [comment]
@jonnycoull 
What banner to put on page? We have now at least three issues, awaiting for your input. If you wont be able to supply all these images today, we'd better replace some of these tasks to tasks from other milestone. Otherwise I'll fail the milestone :-)

**Comment by jonnycoull** [comment]
Sorry @illus0r there all uploaded now. apologies for delay. still working on this one.

**Comment by jonnycoull** [comment]
Hi @illus0r here u go. so image at top of pages....

![pagemock press](https://cloud.githubusercontent.com/assets/17589853/19562488/6f6e61f4-96d4-11e6-932e-ca4f8cee64aa.jpg)

**Comment by jonnycoull** [comment]
Whoops should have cropped that. SO top one is the main bit with list of events, the second is what you see once clicked. So the top name changes to the event name. From PRESS KIT to CODE ACADEMY 2016. 

uploading image now,

**Comment by illus0r** [comment]
@jonnycoull current display differs from mockups. I didn't set left margin of heading, because I used standard control. We can fix it, but this fix should be applied to whole site. That's doable, but requires more time.

Please, reopen this task if you need.

![image](https://cloud.githubusercontent.com/assets/797993/19597878/01a7a208-97a0-11e6-8797-c61ac73bf121.png)


![image](https://cloud.githubusercontent.com/assets/797993/19597836/b793511c-979f-11e6-820e-1e29f015540b.png)


![image](https://cloud.githubusercontent.com/assets/797993/19597852/cbeb8c24-979f-11e6-80e8-384b59b580aa.png)

**Comment by illus0r** [comment]
CI is hanging, so you won't see the changes
