### ISSUE TITLE
Should we enforce a pull --rebase before each deliver?

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#236]
#233 Was caused by an introduction of old code in an update branch

Should we consider enforcing a `git pull --rebase` in our `git deliver` alias?

@JKrag  - any opinions on this?

**Comment by JKrag** [comment]
My initial thoughts are:

a) If a deliver could cause this regression, then it must be because git decided that it was a clean merge. In such case, a git pull --rebase would also just have merged it silently, and it might not have been noticed.

b) git deliver already does enough magic. Adding pull --rebase would add even more complexity. Also, there is the disadvantage that while pull --rebase is really cool, and the right thing to do, its handling of conflicts is very non-trivial to understand for the "not really git users" that are one of the target audience of the smart aliases. I.e. it is hard to explain why you have to fix conflicts and then "git rebase --continue", possibly multiple times.

**Comment by lakruzz** [comment]
Good comment @JKrag
