### ISSUE TITLE
Add "Automation nights Aarhus"  meetup

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#263]
Add this meetup to meetup pages

http://www.meetup.com/CoDe-U-AROS/events/230864013/

**Comment by lakruzz** [comment]
The issue would normally go to the "content update" milestone, which is maintained by Mona, But since the Meetup format is still being worked on by @timea and @illus0r it could be a collaboration btw @timea  and @monaslarsen 

The thing is, we want volume and diversity, to see that the format we create fits the diversity of how we actually use it.

#262 #259 #264

**Comment by timea** [comment]
@lakruzz I spoke with @monaslarsen and we decided to follow the layout of the next gen event. I showed here the includes we have for now and she liked them. This means for now we will have a summary, an agenda, a benefits and workshops include as potential lego blocks. Right now the meetups look very different on meetup.com, we thought to put an agenda on all of them (Oslo does not have one yet)

Any thoughts? Otherwise it is up to @monaslarsen to write the md files.

**Comment by timea** [comment]
The md file is prepared, we will need a main picture for the top, one for the summary, we might keep the one for the agenda from the I'm a github man. Any ideas @lakruzz @jonnycoull ?

**Comment by lakruzz** [comment]
@timea @monaslarsen 

We want to be able to do some of the meetups more "hand held"

As long as we have covered the the markdown in the files (the liquid `{{content}}`) looks fine too - we're OK.

**Comment by lakruzz** [comment]
@timea 

This issue needs to be made ready to work on - but currently needs __an estimate__. I've assigned the case to you, please just do the following:

- Provide a realistic estimate
- Remove the "Action: Needs grooming" label
- Unassign yourself from the issue (just leave the issue unassigned)

**Comment by timea** [comment]
@lakruzz Can you elaborate on "handheld"?

**Comment by timea** [comment]
@jonnycoull as soon as we figure out the pictures, this issue is done.
