### ISSUE TITLE
We need a different cover photo for CoDe Stockholm

### ISSUE THREAD

**Issue by lakruzz** [Praqma/code-conf.com#416]
![image](https://cloud.githubusercontent.com/assets/155492/19678984/519ac2ec-9aa0-11e6-87e0-5e335875246d.png)

...this one is not really selling tickets.

**Comment by lakruzz** [comment]
@monaslarsen @jonnycoull 

Don't know who can own this, but I think it's really important

**Comment by jonnycoull** [comment]
it looks like its been changed to a empty meeting room by someone? which i've tracked down to this website. 

http://meetingroom.se/nyheter/

is this where its held? do you have permission to use this? 
Can I say the bigger you guys get the more likely you are too be sued for pinching pics as there easy to find. @monaslarsen @lakruzz 

![meetingroom_2016](https://cloud.githubusercontent.com/assets/17589853/19692630/8d2b23d0-9ad0-11e6-82a1-fc0bb73c3f64.jpg)

**Comment by jonnycoull** [comment]
I cant seem to access that image library Kruse photos, to select an alternative.

**Comment by monaslarsen** [comment]
Yes, I was thinking exactly the same!
I don't know who picked the current one, but I'll choose a more vibrant one
and get it online asap.

[image: ____________________________________________________________]
Mona Skorstengaard Larsen
Marketing Manager
mona@praqma.com
+45 40 21 95 04 <+45%2040%2021%2095%2004>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>

**Comment by monaslarsen** [comment]
Yes, as stated on the conference site, it's the venue.
Before I put it online, I wrote to ask their management, that I have talked
to earlier, to say that I hoped it was okay that we borrow the picture to
showcase their great venue.
They didn't get back to me today, so I decided to give it a go, since the
former image was straight up sad, and once you've selected an image that we
have the copyrights to, we can just replace it. I did come across this one,
maybe that's a viable alternative?
​
 Conference ambience.tiff
<https://drive.google.com/a/praqma.net/file/d/0B4fPio_UKSleNGxHTHphYmdSWU0/view?usp=drive_web>
​
I'll be away for the next week, but will check my mail every day.
[image: ____________________________________________________________]
Mona Skorstengaard Larsen
Marketing Manager
mona@praqma.com
+45 40 21 95 04 <+45%2040%2021%2095%2004>
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>
