### ISSUE TITLE
Code-Conf frontpage

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#88]
Unless you are in the Praqma organization, entering code-conf.com may seem quite confusing. We have codecph, DOCCPH, CoDeSTHML etc. I suggest we elaborate the abbriviations so it makes sense to people. Please see example below.

![cph_twitter_400_200](https://cloud.githubusercontent.com/assets/8004259/14384903/f0a26912-fd9d-11e5-886b-949e02d8efdb.jpg)

![cph_twitter_400_200 1](https://cloud.githubusercontent.com/assets/8004259/14384905/f35334d4-fd9d-11e5-9f69-3e0681563055.jpg)

**Comment by lakruzz** [comment]
@adamhenriques

Yes please clarify, whatever that can be clarified.

What is the example an example of??

**Comment by adamhenriques** [comment]
@lakruzz I suggest thet we write the conference name in full like; DOC CPH - Day Of Containers - or use graphics like the ones attached with conference name written in full together with conference name

**Comment by lakruzz** [comment]
Agreed, feel free to work it with @jonnycoull

**Comment by adamhenriques** [comment]
@jonnycoull will you generate graphics for the 3 events;

CoDe CPH
Day of Containers, CPH
Day of Containers, STHLM

Either written in full or abbreviations with elaboration below (as shown above with CoDe-CPH)

**Comment by adamhenriques** [comment]
@jonnycoull seems like this was never assigned to you. Will you produce these?

**Comment by jonnycoull** [comment]
the main homepage won't look as it is at the moment. so part of this issue will dissapear soon. currently each sub page has that strap already. to change the copy is a job for @illus0r or @lakruzz possibly? I can't do that its not an image.  if you want to play with the order of the words best speak with them. but its not worth repeating the date as its immediately below. also on here theres 2 mentions of the location so that needs addressing. @adamhenriques so on DOC its like the attached jpg. again these are written in code. ALSO - DOC is orange not just the OC. please amend @illus0r 
![screen shot 2016-04-26 at 08 47 04](https://cloud.githubusercontent.com/assets/17589853/14810572/7c24960e-0b8b-11e6-8bd5-fb5a878217f0.png)

![screen shot 2016-04-26 at 08 42 55](https://cloud.githubusercontent.com/assets/17589853/14810477/15aeca7a-0b8b-11e6-9b04-25dadfcb876c.png)

**Comment by adamhenriques** [comment]
@jonnycoull ok but are the mockups for code-conf.com or the conference specific landingpage? What I would like is elaboration of the conference names on www.code-conf.com.

**Comment by jonnycoull** [comment]
hi @adamhenriques I realise that what I'm trying to explain is main landing page and it isn't finished so what your asking for is actually on another task that I'm working on currently once its resolved the issue you've doubled up on will be resolved. .

**Comment by adamhenriques** [comment]
@jonnycoull great stuff!

**Comment by jonnycoull** [comment]
@adamhenriques what you can assist me on or possible mona too is writing tasters for each item (copy below, which as your full explanation of the event. so my idea is that 4 main events are listed as one main (soonest or biggest) the sub events and a bar of two months. if you want more than that you click to the full listing. if you look at the attached pic i need about 20-25 words summarising the event, quick catch prose to make you want to read more. 
![screen shot 2016-04-26 at 09 02 59](https://cloud.githubusercontent.com/assets/17589853/14811062/12741b3c-0b8e-11e6-8b63-ae0a8e21cffd.png)

**Comment by adamhenriques** [comment]
@jonnycoull Im not quite sure i follow. Moreover, would it make sense to create a individual case of this so we keep things apart?

Lets jump on a hangut when you have time

**Comment by jonnycoull** [comment]
@adamhenriques this is also issue 100 so i think we can close this.

**Comment by adamhenriques** [comment]
Fine

Regards

Adam Henriques
