### ISSUE TITLE
Remove "dummy" sponsors

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#92]
We need to remove "dummy" sponsor logos from CoDe, Doccph and docsthlm events ASAP

**Comment by illus0r** [comment]
@monaslarsen you can just comment sponsor's include out

**Comment by illus0r** [comment]
that's good idea to use `{% comment %} such comments {% endcomment %}`

**Comment by lakruzz** [comment]
@adamhenriques make it a habit to add very specifik links, pics etc to the description, so it's clear what we're talking about:
- [ ] CoDe ...what page are you refering to @adamhenriques ?
- [ ] [Doccph](http://www.code-conf.com/doc-cph-2016/)
- [ ] [docsthlm](http://www.code-conf.com/doc-sthlm-2016/)

**Comment by lakruzz** [comment]
@adamhenriques, @monaslarsen 

I have closed this on now have a look at bef5ea3 this change was easy to fix.  So essentially this is an example on a bad workflow:

* Some crab makes it through to our web site, which was essentials Ivan's test data
* @adamhenriques makes an observation on something that needs to be fixed 
* The description is not very precise, so the make sense of it, it requires some clicking around.
* Even @illus0r comes by and suggest a solution (but _hey_ don't comment stuff out - _delete it_!)
* The issue is assigned to @monaslarsen which apparently has other stuff on her plate
* And all the time container-solutions, delphix, serena and xebia-labs are all listed as sponsors on our conference.

This is truly __URGENT__ - any suggestions to an optimized workflow where things this important , yet simple to solve, don't stall?
